//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvermabApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string RefProv { get; set; }
        public string precio1 { get; set; }
        public string precio2 { get; set; }
        public string precio3 { get; set; }
        public string precio4 { get; set; }
        public string costo { get; set; }
        public Nullable<int> Existencia { get; set; }
    }
}
